FROM python:3.6

# Set the working directory to /var/src
WORKDIR /var/src

# Copy the current directory contents into the container at /var/src
ADD . /var/src

# Make port 80 available to the world outside this container
EXPOSE 80
